const data = {
  'Africa/Abidjan': ['ABJ', 'ASK'],
  'Africa/Accra': ['ACC', 'KMS', 'TML'],
  'Africa/Addis_Ababa': ['ADD', 'AWA', 'DIR', 'JIJ'],
  'Africa/Algiers': [
    'AAE',
    'ALG',
    'BJA',
    'BLJ',
    'BSK',
    'CFK',
    'CZL',
    'DJG',
    'GJL',
    'HME',
    'ORN',
    'QSF',
    'TLM',
    'TMR',
  ],
  'Africa/Asmara': ['ASA', 'ASM', 'MSW'],
  'Africa/Bamako': ['BKO', 'GAQ', 'TOM'],
  'Africa/Bangui': ['BGF'],
  'Africa/Banjul': ['BJL'],
  'Africa/Bissau': ['OXB'],
  'Africa/Blantyre': ['BLZ', 'LLW'],
  'Africa/Brazzaville': ['BZV', 'PNR'],
  'Africa/Bujumbura': ['BJM'],
  'Africa/Cairo': [
    'AAC',
    'ABS',
    'ASW',
    'ATZ',
    'CAI',
    'CCE',
    'DBB',
    'GSQ',
    'HBE',
    'HMB',
    'HRG',
    'LXR',
    'MUH',
    'PSD',
    'RMF',
    'SKV',
    'SPX',
    'SSH',
    'TCP',
  ],
  'Africa/Casablanca': [
    'AGA',
    'BEM',
    'CMN',
    'ESU',
    'FEZ',
    'MLN',
    'NDR',
    'OUD',
    'OZG',
    'OZZ',
    'RAK',
    'RBA',
    'TNG',
    'TTU',
  ],
  'Africa/Conakry': ['CKY'],
  'Africa/Dakar': ['DKR', 'DSS'],
  'Africa/Dar_es_Salaam': ['DAR', 'JRO', 'MWZ', 'ZNZ'],
  'Africa/Djibouti': ['JIB'],
  'Africa/Douala': ['DLA', 'GOU', 'NSI'],
  'Africa/El_Aaiun': ['EUN', 'NDB', 'SMW', 'VIL'],
  'Africa/Freetown': ['FNA'],
  'Africa/Gaborone': ['BBK', 'FRW', 'GBE', 'MUB'],
  'Africa/Harare': ['BUQ', 'HRE', 'MVZ', 'VFA'],
  'Africa/Johannesburg': [
    'BFN',
    'CPT',
    'DUR',
    'ELS',
    'GRJ',
    'HLA',
    'JNB',
    'KIM',
    'MBD',
    'MQP',
    'NTY',
    'OMD',
    'PLZ',
    'PTG',
    'UTN',
  ],
  'Africa/Juba': ['JUB', 'MAK', 'WUU'],
  'Africa/Kampala': ['EBB'],
  'Africa/Khartoum': ['KRT', 'PZU'],
  'Africa/Kigali': ['GOM', 'KGL'],
  'Africa/Kinshasa': ['FIH'],
  'Africa/Lagos': [
    'ABB',
    'ABV',
    'CBQ',
    'ENU',
    'GMO',
    'ILR',
    'KAD',
    'KAN',
    'LOS',
    'MIU',
    'PHC',
    'QOW',
    'SKO',
  ],
  'Africa/Libreville': ['LBV', 'MVB', 'POG'],
  'Africa/Lome': ['LFW', 'LRL'],
  'Africa/Luanda': ['LAD', 'MSZ', 'NBJ', 'SDD'],
  'Africa/Lubumbashi': [
    'BNC',
    'BUX',
    'FBM',
    'FKI',
    'KGA',
    'KND',
    'LJA',
    'MJM',
    'TSH',
  ],
  'Africa/Lusaka': ['LUN', 'LVI', 'MFU', 'NLA'],
  'Africa/Malabo': ['BSG', 'SSG'],
  'Africa/Maputo': ['APL', 'BEW', 'INH', 'MNC', 'MPM', 'POL', 'TET', 'VNX'],
  'Africa/Maseru': ['MSU'],
  'Africa/Mbabane': ['MTS', 'SHO'],
  'Africa/Mogadishu': ['BBO', 'BSA', 'GLK', 'HGA', 'MGQ'],
  'Africa/Monrovia': ['MLW', 'ROB'],
  'Africa/Nairobi': ['EDL', 'KIS', 'MBA', 'MYD', 'NBO', 'WIL', 'WJR'],
  'Africa/Ndjamena': ['NDJ'],
  'Africa/Niamey': ['AJY', 'NIM'],
  'Africa/Nouakchott': ['ATR', 'NKC', 'OUZ'],
  'Africa/Ouagadougou': ['BOY', 'OUA'],
  'Africa/Porto-Novo': ['COO'],
  'Africa/Sao_Tome': ['TMS'],
  'Africa/Tripoli': ['BEN', 'LAQ', 'MJI', 'SRX', 'TIP', 'TOB', 'WAX'],
  'Africa/Tunis': [
    'DJE',
    'GAE',
    'GAF',
    'MIR',
    'NBE',
    'SFA',
    'TBJ',
    'TOE',
    'TUN',
  ],
  'Africa/Windhoek': ['LUD', 'WDH', 'WVB'],
  'America/Adak': ['ADK', 'AKB'],
  'America/Anchorage': [
    'ABL',
    'ANC',
    'BET',
    'BKC',
    'BRW',
    'CDV',
    'FAI',
    'IAN',
    'KKA',
    'KWN',
    'NLG',
    'OBU',
    'ORV',
    'SKK',
    'UNK',
    'WLK',
  ],
  'America/Anguilla': ['AXA'],
  'America/Antigua': ['ANU', 'BBQ'],
  'America/Araguaina': ['AUX', 'CDJ', 'GRP', 'PMW', 'STZ'],
  'America/Argentina/Buenos_Aires': ['AEP', 'BHI', 'EZE', 'MDQ'],
  'America/Argentina/Catamarca': ['CRD', 'CTC', 'EQS', 'PMY', 'REL'],
  'America/Argentina/Cordoba': [
    'COR',
    'FMA',
    'IGR',
    'IGU',
    'PRA',
    'PSS',
    'RES',
    'RHD',
    'ROS',
    'SDE',
    'SFN',
  ],
  'America/Argentina/Jujuy': ['JUJ'],
  'America/Argentina/La_Rioja': ['IRJ'],
  'America/Argentina/Mendoza': ['AFA', 'MDZ'],
  'America/Argentina/Rio_Gallegos': ['FTE', 'RGL'],
  'America/Argentina/Salta': ['BRC', 'CPC', 'NQN', 'RSA', 'SLA', 'VDM'],
  'America/Argentina/San_Juan': ['UAQ'],
  'America/Argentina/San_Luis': ['LUQ', 'RLO'],
  'America/Argentina/Tucuman': ['TUC'],
  'America/Argentina/Ushuaia': ['RGA', 'USH'],
  'America/Aruba': ['AUA'],
  'America/Asuncion': ['AGT', 'ASU', 'ENO', 'ESG'],
  'America/Atikokan': ['YPL', 'YZS'],
  'America/Bahia': ['BPS', 'BRA', 'IOS', 'SSA', 'VDC'],
  'America/Bahia_Banderas': ['PVR'],
  'America/Barbados': ['BGI'],
  'America/Belem': ['BEL', 'CKS', 'MAB', 'MCP', 'RDC'],
  'America/Belize': ['BZE'],
  'America/Blanc-Sablon': ['YBX', 'YNA'],
  'America/Boa_Vista': ['BVB'],
  'America/Bogota': [
    'ADZ',
    'AXM',
    'BAQ',
    'BGA',
    'BOG',
    'CLO',
    'CTG',
    'CUC',
    'LET',
    'MDE',
    'PEI',
    'PYH',
    'SMR',
    'SVZ',
    'TBT',
  ],
  'America/Boise': ['BOI', 'IDA', 'PIH', 'TWF'],
  'America/Cambridge_Bay': ['YCB', 'YCO', 'YHK', 'YYH'],
  'America/Campo_Grande': ['BYO', 'CGR', 'CMG', 'DOU'],
  'America/Cancun': ['CTM', 'CUN', 'CZM', 'TQO'],
  'America/Caracas': [
    'BLA',
    'BRM',
    'CCS',
    'LSP',
    'MAR',
    'MUN',
    'PBL',
    'PMV',
    'PZO',
    'STD',
    'VLN',
  ],
  'America/Cayenne': ['CAY'],
  'America/Cayman': ['CYB', 'GCM'],
  'America/Chicago': [
    'AEX',
    'AMA',
    'ATW',
    'AUS',
    'BHM',
    'BIS',
    'BKG',
    'BLV',
    'BMI',
    'BNA',
    'BTR',
    'CID',
    'DAL',
    'DDC',
    'DFW',
    'DHN',
    'DRT',
    'DSM',
    'EAR',
    'ECP',
    'EVV',
    'FAR',
    'FSD',
    'GFK',
    'GLS',
    'GRI',
    'GRK',
    'GTR',
    'HOU',
    'HRL',
    'HSV',
    'IAH',
    'ICT',
    'JAN',
    'LBB',
    'LBF',
    'LBL',
    'LFT',
    'LIT',
    'LNK',
    'LRD',
    'MAF',
    'MCI',
    'MCK',
    'MDW',
    'MEM',
    'MFE',
    'MGM',
    'MKE',
    'MLI',
    'MLU',
    'MOB',
    'MOT',
    'MSL',
    'MSN',
    'MSP',
    'MSY',
    'OKC',
    'OMA',
    'ORD',
    'PIA',
    'PIR',
    'PNS',
    'RFD',
    'RST',
    'SAT',
    'SGF',
    'SHV',
    'SPI',
    'STC',
    'STL',
    'TUL',
    'VPS',
    'XNA',
    'XWA',
  ],
  'America/Chihuahua': ['CUU'],
  'America/Ciudad_Juarez': ['CJS'],
  'America/Costa_Rica': ['LIO', 'LIR', 'SJO', 'SYQ'],
  'America/Cuiaba': ['CGB', 'OPS', 'SXO'],
  'America/Curacao': ['CUR'],
  'America/Dawson_Creek': ['YDQ', 'YXJ'],
  'America/Denver': [
    'ABQ',
    'ASE',
    'BIL',
    'BZN',
    'COS',
    'CPR',
    'CTB',
    'DEN',
    'DIK',
    'DRO',
    'ELP',
    'FCA',
    'FMN',
    'GJT',
    'GTF',
    'HLN',
    'HOB',
    'LRU',
    'MSO',
    'OGD',
    'PVU',
    'RAP',
    'ROW',
    'SAF',
    'SLC',
    'SVC',
  ],
  'America/Detroit': [
    'APN',
    'AZO',
    'CIU',
    'CMX',
    'DTW',
    'FNT',
    'GRR',
    'LAN',
    'MBL',
    'MBS',
    'MKG',
    'MQT',
    'PHN',
    'PTK',
    'TVC',
    'YAM',
  ],
  'America/Dominica': ['DOM'],
  'America/Edmonton': ['YEG', 'YHI', 'YMM', 'YQF', 'YXC', 'YYC', 'YZF'],
  'America/Eirunepe': ['ERN'],
  'America/El_Salvador': ['ILS', 'SAL'],
  'America/Fort_Nelson': ['YYE'],
  'America/Fortaleza': [
    'CPV',
    'FOR',
    'IMP',
    'JDO',
    'JPA',
    'NAT',
    'PHB',
    'SLZ',
    'THE',
  ],
  'America/Glace_Bay': ['YQY'],
  'America/Goose_Bay': ['YWK', 'YYR'],
  'America/Grand_Turk': ['GDT', 'PLS'],
  'America/Grenada': ['GND'],
  'America/Guadeloupe': ['PTP'],
  'America/Guatemala': ['FRS', 'GUA'],
  'America/Guayaquil': ['ESM', 'ETR', 'GYE', 'LTX', 'MEC', 'SNC', 'TUA', 'UIO'],
  'America/Guyana': ['GEO', 'OGL'],
  'America/Halifax': ['YGR', 'YHZ', 'YYG'],
  'America/Havana': [
    'CCC',
    'CMW',
    'CYO',
    'HAV',
    'HOG',
    'MZO',
    'SCU',
    'SNU',
    'VRA',
  ],
  'America/Hermosillo': ['CEN', 'GYM', 'HMO', 'NOG', 'PPE'],
  'America/Indiana/Indianapolis': ['FWA', 'IND', 'SBN'],
  'America/Inuvik': ['YEV', 'YFS', 'YSY', 'YVQ', 'YWJ'],
  'America/Iqaluit': [
    'YFB',
    'YGW',
    'YGZ',
    'YIK',
    'YKQ',
    'YNC',
    'YPX',
    'YQC',
    'YSK',
    'YTE',
    'YUD',
  ],
  'America/Jamaica': ['KIN', 'MBJ', 'OCJ'],
  'America/Juneau': ['JNU'],
  'America/Kentucky/Louisville': ['SDF'],
  'America/Kralendijk': ['BON', 'EUX', 'SAB'],
  'America/La_Paz': ['CBB', 'LPB', 'ORU', 'SRE', 'VVI'],
  'America/Lima': [
    'AQP',
    'ARI',
    'CIX',
    'CUZ',
    'IQT',
    'JUL',
    'LIM',
    'PCL',
    'PEM',
    'PIO',
    'PIU',
    'TBP',
    'TCQ',
    'TRU',
    'TYL',
  ],
  'America/Los_Angeles': [
    'BFI',
    'BFL',
    'BLD',
    'BLI',
    'BUR',
    'CLM',
    'CXL',
    'EKO',
    'EUG',
    'FAT',
    'GEG',
    'LAS',
    'LAX',
    'LGB',
    'LWS',
    'MFR',
    'MRY',
    'MWH',
    'OAK',
    'ONT',
    'PAE',
    'PDX',
    'PSC',
    'PSP',
    'RDM',
    'RNO',
    'SAN',
    'SBA',
    'SBD',
    'SBP',
    'SEA',
    'SFO',
    'SJC',
    'SMF',
    'SNA',
    'TIJ',
    'YXX',
  ],
  'America/Lower_Princes': ['SFG', 'SXM'],
  'America/Maceio': ['AJU', 'MCZ'],
  'America/Managua': ['MGA'],
  'America/Manaus': ['MAO', 'TFF'],
  'America/Martinique': ['FDF'],
  'America/Matamoros': ['ACN', 'MAM', 'NLD', 'PDS', 'REX'],
  'America/Mazatlan': ['CUL', 'LAP', 'LMM', 'LTO', 'MZT', 'SJD', 'TPQ'],
  'America/Merida': ['CME', 'CPE', 'CZA', 'MID'],
  'America/Mexico_City': [
    'ACA',
    'AGU',
    'BJX',
    'CLQ',
    'CVJ',
    'GDL',
    'HUX',
    'MEX',
    'MLM',
    'MTT',
    'NLU',
    'OAX',
    'PAZ',
    'PBC',
    'PQM',
    'PXM',
    'QRO',
    'SLP',
    'TAP',
    'TGZ',
    'TLC',
    'UPN',
    'VER',
    'VSA',
    'ZCL',
    'ZIH',
    'ZLO',
  ],
  'America/Miquelon': ['FSP'],
  'America/Moncton': ['HUL', 'YCL', 'YFC', 'YQM', 'YSJ', 'ZBF'],
  'America/Monterrey': ['CVM', 'DGO', 'LOV', 'MTY', 'NTR', 'SLW', 'TAM', 'TRC'],
  'America/Montevideo': ['ATI', 'CYR', 'DZO', 'MLZ', 'MVD', 'PDP', 'STY'],
  'America/Montserrat': ['MNI'],
  'America/Nassau': [
    'BIM',
    'ELH',
    'FPO',
    'GGT',
    'GHB',
    'MHH',
    'NAS',
    'RCY',
    'RSD',
    'TCB',
    'ZSA',
  ],
  'America/New_York': [
    'ABE',
    'ACY',
    'AHN',
    'ALB',
    'ART',
    'ATL',
    'AVL',
    'AVP',
    'BDL',
    'BOS',
    'BTV',
    'BUF',
    'BWI',
    'CAE',
    'CAK',
    'CHA',
    'CHO',
    'CHS',
    'CLE',
    'CLT',
    'CMH',
    'CVG',
    'DAY',
    'DCA',
    'ELM',
    'EWR',
    'EYW',
    'FLL',
    'GSO',
    'GSP',
    'HPN',
    'IAD',
    'JAX',
    'JFK',
    'LEX',
    'LGA',
    'LUK',
    'MCO',
    'MDT',
    'MHT',
    'MIA',
    'MYR',
    'ORF',
    'PBI',
    'PGD',
    'PHF',
    'PHL',
    'PIE',
    'PIT',
    'PVD',
    'PWM',
    'RDU',
    'RIC',
    'ROA',
    'ROC',
    'RSW',
    'SAV',
    'SCE',
    'SFB',
    'SRQ',
    'SYR',
    'TLH',
    'TOL',
    'TPA',
    'TTN',
    'TYS',
  ],
  'America/Nome': [
    'CDB',
    'CYF',
    'DRG',
    'DUT',
    'EEK',
    'ELI',
    'EMK',
    'KKH',
    'KPN',
    'KSM',
    'KWK',
    'MYU',
    'OME',
    'OTZ',
    'PIZ',
    'SCM',
    'SMK',
    'SNP',
    'STG',
    'WWT',
  ],
  'America/Noronha': ['FEN'],
  'America/Nuuk': ['GOH', 'JUV', 'KUS', 'SFJ', 'UAK'],
  'America/Panama': ['BLB', 'BOC', 'CHX', 'DAV', 'PAC', 'PTY', 'RIH'],
  'America/Paramaribo': ['PBM'],
  'America/Phoenix': [
    'AZA',
    'DUG',
    'GCW',
    'IFP',
    'IGM',
    'OLS',
    'PGA',
    'PHX',
    'PRC',
    'SOW',
    'TUS',
    'YUM',
  ],
  'America/Port-au-Prince': ['CAP', 'CYA', 'PAP'],
  'America/Port_of_Spain': ['POS', 'TAB'],
  'America/Porto_Velho': ['BVH', 'JPR', 'OAL', 'PVH'],
  'America/Puerto_Rico': ['BQN', 'PSE', 'SJU', 'VQS'],
  'America/Punta_Arenas': ['PUQ'],
  'America/Rankin_Inlet': ['YAB', 'YCS', 'YEK', 'YRT', 'YUT'],
  'America/Recife': ['PNZ', 'REC'],
  'America/Regina': ['YQR', 'YXE'],
  'America/Resolute': ['YRB'],
  'America/Rio_Branco': ['RBR'],
  'America/Santarem': ['ATM', 'MEU', 'STM'],
  'America/Santiago': ['ANF', 'BBA', 'CCP', 'IQQ', 'PMC', 'SCL', 'ZCO'],
  'America/Santo_Domingo': [
    'AZS',
    'BRX',
    'JBQ',
    'LRM',
    'POP',
    'PUJ',
    'SDQ',
    'STI',
  ],
  'America/Sao_Paulo': [
    'BSB',
    'CGH',
    'CNF',
    'CWB',
    'FLN',
    'GIG',
    'GRU',
    'GYN',
    'LDB',
    'MGF',
    'NVT',
    'PET',
    'PLU',
    'POA',
    'QSC',
    'SDU',
    'SJP',
    'VCP',
    'VIX',
  ],
  'America/Scoresbysund': ['CNP'],
  'America/Sitka': ['KTN', 'PSG', 'SIT'],
  'America/St_Barthelemy': ['SBH'],
  'America/St_Johns': ['YAY', 'YDF', 'YJT', 'YQX', 'YYT'],
  'America/St_Kitts': ['NEV', 'SKB'],
  'America/St_Lucia': ['SLU', 'UVF'],
  'America/St_Thomas': ['STT', 'STX'],
  'America/St_Vincent': ['SVD', 'UNI'],
  'America/Tegucigalpa': ['LCE', 'RTB', 'SAP', 'TGU', 'XPL'],
  'America/Thule': ['NAQ', 'THU'],
  'America/Tijuana': ['ESE', 'MXL', 'SFH'],
  'America/Toronto': [
    'SUR',
    'YBC',
    'YBG',
    'YER',
    'YGL',
    'YGP',
    'YHM',
    'YKF',
    'YKG',
    'YKL',
    'YKU',
    'YMO',
    'YMT',
    'YMX',
    'YNS',
    'YOW',
    'YPH',
    'YQB',
    'YQG',
    'YQT',
    'YSB',
    'YTM',
    'YTZ',
    'YUL',
    'YUY',
    'YVB',
    'YVO',
    'YVP',
    'YWB',
    'YWP',
    'YXU',
    'YYY',
    'YYZ',
    'YZG',
    'YZV',
  ],
  'America/Tortola': ['EIS', 'VIJ'],
  'America/Vancouver': [
    'YCD',
    'YCG',
    'YKA',
    'YLW',
    'YQQ',
    'YVR',
    'YXS',
    'YYJ',
    'YZY',
  ],
  'America/Whitehorse': ['YXY'],
  'America/Winnipeg': ['WNN', 'YAG', 'YBR', 'YHD', 'YTL', 'YWG', 'YXL', 'YYQ'],
  'America/Yakutat': ['YAK'],
  'Arctic/Longyearbyen': ['LYR'],
  'Asia/Aden': ['AAY', 'ADE', 'GXF', 'HOD', 'RIY', 'SAH', 'TAI'],
  'Asia/Almaty': [
    'ALA',
    'CIT',
    'DMB',
    'DZN',
    'HSA',
    'KGF',
    'KOV',
    'NQZ',
    'PLX',
    'PPK',
    'PWQ',
    'UKK',
  ],
  'Asia/Amman': ['ADJ', 'AMM', 'AQJ', 'ETH', 'ETM'],
  'Asia/Aqtau': ['SCO'],
  'Asia/Aqtobe': ['AKX'],
  'Asia/Ashgabat': ['ASB', 'CRZ', 'KRW', 'MYP'],
  'Asia/Atyrau': ['GUW'],
  'Asia/Baghdad': ['BGW', 'BSR', 'EBL', 'ISU', 'KIK', 'NJF'],
  'Asia/Bahrain': ['BAH'],
  'Asia/Baku': ['GBB', 'GNJ', 'GYD', 'LLK', 'NAJ', 'ZTU', 'ZZE'],
  'Asia/Bangkok': [
    'BKK',
    'BTZ',
    'CEI',
    'CNX',
    'DMK',
    'HAN',
    'HDY',
    'HKT',
    'HPH',
    'KBV',
    'THD',
    'URT',
    'USM',
    'UTH',
    'UTP',
    'VDH',
    'VDO',
    'VII',
    'ZVK',
  ],
  'Asia/Beirut': ['BEY'],
  'Asia/Bishkek': ['BSZ', 'IKU', 'OSS'],
  'Asia/Brunei': ['BWN', 'LMN'],
  'Asia/Choibalsan': ['COQ'],
  'Asia/Colombo': ['BTC', 'CMB', 'HRI', 'JAF', 'RML'],
  'Asia/Damascus': ['ALP', 'DAM', 'KAC', 'LTK'],
  'Asia/Dhaka': ['CGP', 'DAC', 'ZYL'],
  'Asia/Dili': ['DIL', 'OEC', 'UAI'],
  'Asia/Dubai': ['AAN', 'AUH', 'AZI', 'DWC', 'DXB', 'FJR', 'RKT', 'SHJ'],
  'Asia/Dushanbe': ['DYU', 'KQT', 'LBD', 'TJU'],
  'Asia/Famagusta': ['ECN'],
  'Asia/Ho_Chi_Minh': [
    'BMV',
    'CXR',
    'DAD',
    'DLI',
    'HUI',
    'PQC',
    'PXU',
    'SGN',
    'TBB',
    'UIH',
    'VCA',
    'VCL',
  ],
  'Asia/Hong_Kong': ['HKG'],
  'Asia/Hovd': ['HVD', 'LTI', 'ULG', 'ULO'],
  'Asia/Jakarta': [
    'BDO',
    'BTH',
    'BTJ',
    'CGK',
    'HLP',
    'JOG',
    'KJT',
    'KNO',
    'MLG',
    'PDG',
    'PKU',
    'PLM',
    'SOC',
    'SRG',
    'SUB',
    'TJQ',
    'TKG',
    'TNJ',
    'YIA',
  ],
  'Asia/Jayapura': [
    'AMQ',
    'BIK',
    'DJJ',
    'KAZ',
    'MKQ',
    'MKW',
    'SOQ',
    'TIM',
    'TTE',
  ],
  'Asia/Jerusalem': ['HFA', 'SDV', 'TLV', 'VDA'],
  'Asia/Kabul': ['HEA', 'KBL', 'KDH', 'KHT', 'MZR'],
  'Asia/Karachi': [
    'DEA',
    'GWD',
    'ISB',
    'KDU',
    'KHI',
    'LHE',
    'LYP',
    'MUX',
    'PEW',
    'RYK',
    'SKT',
    'SKZ',
    'TUK',
    'UET',
  ],
  'Asia/Kathmandu': ['BWA', 'KTM', 'PHH'],
  'Asia/Kolkata': [
    'AMD',
    'ATQ',
    'AYJ',
    'BBI',
    'BDQ',
    'BHO',
    'BLR',
    'BOM',
    'CCJ',
    'CCU',
    'CJB',
    'CNN',
    'COK',
    'DEL',
    'DXN',
    'GAU',
    'GOI',
    'GOX',
    'HSR',
    'HSS',
    'HYD',
    'IDR',
    'IMF',
    'ISK',
    'IXB',
    'IXC',
    'IXE',
    'IXM',
    'IXZ',
    'JAI',
    'KBK',
    'LKO',
    'MAA',
    'NAG',
    'PNQ',
    'SAG',
    'STV',
    'SXR',
    'TIR',
    'TRV',
    'TRZ',
    'VGA',
    'VNS',
    'VTZ',
  ],
  'Asia/Kuala_Lumpur': [
    'IPH',
    'JHB',
    'KBR',
    'KUA',
    'KUL',
    'LGK',
    'MKZ',
    'PEN',
    'RDN',
    'SZB',
    'TGG',
  ],
  'Asia/Kuching': [
    'BKI',
    'BTU',
    'KCH',
    'LBU',
    'MYY',
    'MZV',
    'SBW',
    'SDK',
    'TWU',
  ],
  'Asia/Kuwait': ['KWI'],
  'Asia/Macau': ['MFM'],
  'Asia/Makassar': [
    'AAP',
    'BDJ',
    'BPN',
    'DPS',
    'KDI',
    'KOE',
    'LOP',
    'MDC',
    'PLW',
    'TRK',
    'UPG',
  ],
  'Asia/Manila': [
    'BCD',
    'CEB',
    'CGY',
    'CRK',
    'DRP',
    'DVO',
    'GES',
    'ILO',
    'KLO',
    'LAO',
    'MNL',
    'PPS',
    'SFS',
    'TAG',
    'ZAM',
  ],
  'Asia/Muscat': ['DQM', 'MCT', 'OHS', 'SLL'],
  'Asia/Nicosia': ['LCA', 'PFO'],
  'Asia/Oral': ['URA'],
  'Asia/Phnom_Penh': ['KOS', 'KTI', 'PNH', 'REP', 'SAI'],
  'Asia/Pontianak': ['PKN', 'PKY', 'PNK'],
  'Asia/Pyongyang': ['FNJ'],
  'Asia/Qatar': ['DIA', 'DOH'],
  'Asia/Qostanay': ['KSN'],
  'Asia/Qyzylorda': ['BXY', 'KZO'],
  'Asia/Riyadh': [
    'AHB',
    'AJF',
    'DHA',
    'DMM',
    'ELQ',
    'HAS',
    'HOF',
    'JED',
    'MED',
    'NUM',
    'RSI',
    'RUH',
    'TIF',
    'TUU',
    'ULH',
    'YNB',
  ],
  'Asia/Samarkand': ['BHK', 'KSQ', 'NCU', 'NVI', 'SKD', 'TMJ', 'UGC'],
  'Asia/Seoul': ['CJJ', 'CJU', 'GMP', 'ICN', 'MWX', 'PUS', 'TAE', 'YNY'],
  'Asia/Singapore': ['SIN'],
  'Asia/Taipei': ['HUN', 'KHH', 'RMQ', 'TNN', 'TPE', 'TSA'],
  'Asia/Tashkent': ['AZN', 'FEG', 'NMA', 'TAS'],
  'Asia/Tbilisi': ['BUS', 'KUT', 'SUI', 'TBS'],
  'Asia/Tehran': [
    'ABD',
    'AWZ',
    'AZD',
    'BDH',
    'BND',
    'BUZ',
    'GBT',
    'GSM',
    'IFN',
    'IKA',
    'KER',
    'KIH',
    'KSH',
    'LFM',
    'LRR',
    'MHD',
    'OMH',
    'PGU',
    'PYK',
    'RAS',
    'RUD',
    'SRY',
    'SYZ',
    'TBZ',
    'THR',
    'XBJ',
    'ZAH',
    'ZBR',
  ],
  'Asia/Thimphu': ['PBH'],
  'Asia/Tokyo': [
    'AKJ',
    'AOJ',
    'AXT',
    'CTS',
    'FSZ',
    'FUK',
    'HIJ',
    'HKD',
    'HND',
    'HSG',
    'IBR',
    'ISG',
    'KCZ',
    'KIJ',
    'KIX',
    'KKJ',
    'KMI',
    'KMJ',
    'KMQ',
    'KOJ',
    'MYJ',
    'NGO',
    'NRT',
    'OIT',
    'OKA',
    'OKJ',
    'SDJ',
    'TAK',
    'TOY',
    'UKB',
    'YGJ',
  ],
  'Asia/Ulaanbaatar': ['BYN', 'UBN', 'ULN'],
  'Asia/Vientiane': ['LPQ', 'PKZ', 'VTE'],
  'Asia/Yangon': ['MDL', 'NYT', 'RGN'],
  'Asia/Yerevan': ['EVN', 'LWN'],
  'Atlantic/Azores': ['HOR', 'PDL', 'TER'],
  'Atlantic/Bermuda': ['BDA'],
  'Atlantic/Canary': ['ACE', 'FUE', 'LPA', 'SPC', 'TFN', 'TFS'],
  'Atlantic/Cape_Verde': ['BVC', 'RAI', 'SID', 'VXE'],
  'Atlantic/Faroe': ['FAE'],
  'Atlantic/Madeira': ['FNC', 'PXO'],
  'Atlantic/Reykjavik': ['AEY', 'KEF', 'RKV'],
  'Atlantic/St_Helena': ['HLE'],
  'Atlantic/Stanley': ['MPN'],
  'Australia/Adelaide': ['ADL', 'MGB'],
  'Australia/Brisbane': [
    'BNE',
    'CNS',
    'GLT',
    'HVB',
    'ISA',
    'MCY',
    'MKY',
    'OOL',
    'PPP',
    'TSV',
    'TWB',
    'WTB',
  ],
  'Australia/Broken_Hill': ['BHQ'],
  'Australia/Darwin': ['ASP', 'AYQ', 'DRW', 'GOV', 'GTE'],
  'Australia/Hobart': ['BWT', 'DPO', 'HBA', 'KNS', 'LST'],
  'Australia/Lindeman': ['HTI'],
  'Australia/Lord_Howe': ['LDH'],
  'Australia/Melbourne': ['ABX', 'AVV', 'MEB', 'MEL', 'MQL'],
  'Australia/Perth': ['BME', 'KNX', 'PER'],
  'Australia/Sydney': [
    'BNK',
    'CBR',
    'CFS',
    'DBO',
    'MIM',
    'NTL',
    'PQQ',
    'SYD',
    'WGA',
  ],
  'Europe/Amsterdam': ['AMS', 'EIN', 'GRQ', 'MST', 'NRN', 'RTM'],
  'Europe/Athens': [
    'ATH',
    'CFU',
    'CHQ',
    'EFL',
    'GPA',
    'HER',
    'JMK',
    'JTR',
    'KGS',
    'KLX',
    'KVA',
    'MJT',
    'PVK',
    'RHO',
    'SKG',
    'SMI',
    'VOL',
    'ZTH',
  ],
  'Europe/Belgrade': ['BEG', 'INI', 'PRN'],
  'Europe/Berlin': [
    'AGB',
    'BER',
    'BRE',
    'CGN',
    'DRS',
    'DTM',
    'DUS',
    'ERF',
    'FDH',
    'FKB',
    'FMM',
    'FMO',
    'FRA',
    'GWT',
    'HAJ',
    'HAM',
    'HHN',
    'KSF',
    'LBC',
    'LEJ',
    'MUC',
    'NUE',
    'PAD',
    'RLG',
    'SCN',
    'STR',
    'SZG',
    'TXL',
    'XFW',
    'ZQW',
  ],
  'Europe/Bratislava': ['BTS', 'KSC', 'UDJ'],
  'Europe/Brussels': ['ANR', 'BRU', 'CRL', 'KJK', 'LGG', 'OST'],
  'Europe/Bucharest': [
    'ARW',
    'BAY',
    'BBU',
    'BCM',
    'CLJ',
    'CND',
    'CRA',
    'GHV',
    'IAS',
    'OMR',
    'OTP',
    'SBZ',
    'SCV',
    'SUJ',
    'TGM',
    'TSR',
  ],
  'Europe/Budapest': ['BUD', 'DEB', 'PEV'],
  'Europe/Chisinau': ['BZY', 'RMO'],
  'Europe/Copenhagen': ['AAL', 'AAR', 'BLL', 'CPH', 'EBJ', 'ODE'],
  'Europe/Dublin': ['CFN', 'DUB', 'KIR', 'NOC', 'ORK', 'SNN', 'WAT'],
  'Europe/Gibraltar': ['GIB'],
  'Europe/Guernsey': ['ACI', 'GCI'],
  'Europe/Helsinki': [
    'HEL',
    'IVL',
    'KTT',
    'KUO',
    'LPP',
    'OUL',
    'POR',
    'RVN',
    'TKU',
    'TMP',
    'VAA',
  ],
  'Europe/Isle_of_Man': ['IOM'],
  'Europe/Istanbul': [
    'ADA',
    'ADB',
    'AOE',
    'ASR',
    'AYT',
    'BJV',
    'COV',
    'DLM',
    'EDO',
    'ERZ',
    'ESB',
    'GNY',
    'GZP',
    'GZT',
    'HTY',
    'ISE',
    'ISL',
    'IST',
    'KYA',
    'NAV',
    'ONQ',
    'RZV',
    'SAW',
    'TZX',
  ],
  'Europe/Jersey': ['JER'],
  'Europe/Kyiv': [
    'CKC',
    'CWC',
    'DNK',
    'DOK',
    'HRK',
    'IEV',
    'IFO',
    'KBP',
    'KHE',
    'KWG',
    'LWO',
    'MPW',
    'ODS',
    'OZH',
    'RWN',
    'TNL',
    'VIN',
  ],
  'Europe/Lisbon': ['FAO', 'LIS', 'OPO'],
  'Europe/Ljubljana': ['LJU'],
  'Europe/London': [
    'ABZ',
    'BFS',
    'BHD',
    'BHX',
    'BLK',
    'BOH',
    'BRS',
    'CEG',
    'CWL',
    'DSA',
    'EDI',
    'EMA',
    'EXT',
    'GLA',
    'GLO',
    'HUY',
    'INV',
    'LBA',
    'LCY',
    'LDY',
    'LGW',
    'LHR',
    'LPL',
    'LTN',
    'MAN',
    'MME',
    'NCL',
    'NQY',
    'NWI',
    'PIK',
    'SEN',
    'SOU',
    'STN',
  ],
  'Europe/Luxembourg': ['LUX'],
  'Europe/Madrid': [
    'AGP',
    'ALC',
    'BCN',
    'BIO',
    'CQM',
    'GRO',
    'GRX',
    'IBZ',
    'LCG',
    'LEI',
    'LEN',
    'MAD',
    'MAH',
    'MJV',
    'OVD',
    'PMI',
    'REU',
    'RMU',
    'SCQ',
    'SDR',
    'SVQ',
    'VGO',
    'VLC',
    'XRY',
    'ZAZ',
  ],
  'Europe/Malta': ['MLA'],
  'Europe/Mariehamn': ['MHQ'],
  'Europe/Minsk': ['BQT', 'MSQ'],
  'Europe/Oslo': [
    'AES',
    'BGO',
    'BOO',
    'EVE',
    'HAU',
    'KRS',
    'KSU',
    'MOL',
    'OSL',
    'RYG',
    'SVG',
    'TOS',
    'TRD',
    'TRF',
  ],
  'Europe/Paris': [
    'AJA',
    'BES',
    'BIA',
    'BIQ',
    'BOD',
    'BOR',
    'BSL',
    'BVA',
    'BVE',
    'BZR',
    'CCF',
    'CDG',
    'CFE',
    'CLY',
    'DLE',
    'DNR',
    'DOL',
    'EBU',
    'EGC',
    'ETZ',
    'FNI',
    'FSC',
    'GVA',
    'LBG',
    'LDE',
    'LIG',
    'LIL',
    'LRH',
    'LYS',
    'MLH',
    'MPL',
    'MRS',
    'NCE',
    'NTE',
    'ORY',
    'PGF',
    'PIS',
    'RDZ',
    'RNS',
    'SXB',
    'TLN',
    'TLS',
    'TUF',
    'XCR',
  ],
  'Europe/Podgorica': ['TGD', 'TIV'],
  'Europe/Prague': ['BRQ', 'KLV', 'OSR', 'PED', 'PRG'],
  'Europe/Riga': ['DGP', 'LPX', 'RIX', 'VNT'],
  'Europe/Rome': [
    'AHO',
    'AOI',
    'BDS',
    'BGY',
    'BLQ',
    'BRI',
    'CAG',
    'CIA',
    'CIY',
    'CTA',
    'CUF',
    'FCO',
    'FLR',
    'FRL',
    'GOA',
    'LIN',
    'MXP',
    'NAP',
    'OLB',
    'PEG',
    'PMF',
    'PMO',
    'PSA',
    'PSR',
    'RMI',
    'SUF',
    'TPS',
    'TRN',
    'TRS',
    'TSF',
    'VCE',
    'VRN',
  ],
  'Europe/Sarajevo': ['BNX', 'OMO', 'SJJ', 'TZL'],
  'Europe/Simferopol': ['SIP', 'UKS'],
  'Europe/Skopje': ['OHD', 'SKP'],
  'Europe/Sofia': ['BOJ', 'PDV', 'SOF', 'VAR'],
  'Europe/Stockholm': [
    'ARN',
    'BMA',
    'GOT',
    'GSE',
    'KRN',
    'KSD',
    'LLA',
    'LPI',
    'MMX',
    'NRK',
    'NYO',
    'OSD',
    'PJA',
    'SCR',
    'SFT',
    'TYF',
    'UME',
    'VBY',
    'VST',
    'VXO',
  ],
  'Europe/Tallinn': ['TAY', 'TLL'],
  'Europe/Tirane': ['KFZ', 'TIA'],
  'Europe/Vienna': ['ACH', 'GRZ', 'INN', 'KLU', 'LNZ', 'VIE'],
  'Europe/Vilnius': ['KUN', 'PLQ', 'SQQ', 'VNO'],
  'Europe/Warsaw': [
    'BZG',
    'GDN',
    'KRK',
    'KTW',
    'LCJ',
    'LUZ',
    'POZ',
    'RZE',
    'SZZ',
    'WAW',
    'WMI',
    'WRO',
  ],
  'Europe/Zagreb': ['DBV', 'OSI', 'PUY', 'RJK', 'SPU', 'ZAD', 'ZAG'],
  'Europe/Zurich': ['BRN', 'LUG', 'ZRH'],
  'Indian/Antananarivo': ['DIE', 'MJN', 'NOS', 'SMS', 'TMM', 'TNR'],
  'Indian/Christmas': ['XCH'],
  'Indian/Cocos': ['CCK'],
  'Indian/Comoro': ['HAH'],
  'Indian/Mahe': ['SEZ'],
  'Indian/Maldives': ['GAN', 'HAQ', 'MLE', 'NMF', 'VAM'],
  'Indian/Mauritius': ['MRU'],
  'Indian/Mayotte': ['DZA'],
  'Indian/Reunion': ['RUN', 'ZSE'],
  'Pacific/Apia': ['APW'],
  'Pacific/Auckland': ['AKL', 'CHC', 'DUD', 'HLZ', 'WLG', 'ZQN'],
  'Pacific/Bougainville': ['BUA'],
  'Pacific/Chuuk': ['TKK', 'YAP'],
  'Pacific/Easter': ['IPC'],
  'Pacific/Efate': ['SON', 'VLI'],
  'Pacific/Fiji': ['NAN', 'SUV'],
  'Pacific/Funafuti': ['FUN'],
  'Pacific/Galapagos': ['GPS', 'SCY'],
  'Pacific/Gambier': ['GMR'],
  'Pacific/Guadalcanal': ['HIR'],
  'Pacific/Guam': ['GUM'],
  'Pacific/Honolulu': ['HNL', 'ITO', 'KOA', 'LIH', 'OGG'],
  'Pacific/Kiritimati': ['CXI'],
  'Pacific/Kosrae': ['KSA'],
  'Pacific/Kwajalein': ['KWA'],
  'Pacific/Majuro': ['MAJ'],
  'Pacific/Marquesas': ['AUQ', 'NHV'],
  'Pacific/Nauru': ['INU'],
  'Pacific/Niue': ['IUE'],
  'Pacific/Norfolk': ['NLK'],
  'Pacific/Noumea': ['NOU'],
  'Pacific/Pago_Pago': ['PPG'],
  'Pacific/Palau': ['ROR'],
  'Pacific/Pohnpei': ['PNI'],
  'Pacific/Port_Moresby': ['LAE', 'MIS', 'POM', 'RAB', 'WWK'],
  'Pacific/Rarotonga': ['RAR'],
  'Pacific/Saipan': ['ROP', 'SPN', 'TIQ'],
  'Pacific/Tahiti': ['HOI', 'PPT'],
  'Pacific/Tarawa': ['TRW'],
  'Pacific/Tongatapu': ['TBU', 'VAV'],
  'Pacific/Wallis': ['WLS'],
}

const iataTimezone = Object.entries(data).reduce(
  (result, [timezone, airports]) => {
    airports.forEach(airport => {
      result[airport] = timezone
    })
    return result
  },
  {},
)

export default iataTimezone
